### PR TITLE
Remove Roc submodule, in favor of recommended installation

### PR DESCRIPTION
**Pull request by kili-ilo**

### CODE REVIEW

**Comment by kili-ilo** [comment]
@Anton-4 What the heck?
```
[jan@framey roc-plotters]$ roc examples/hello_world.roc 
roc: /lib64/libtinfo.so.6: no version information available (required by roc)
── FILE PROBLEM ────────────────────────────────────────────────── UNKNOWN.roc ─

I tried to read this file, but ran into a is a directory problem.[jan@framey roc-plotters]$ which roc
~/.local/bin/roc
[jan@framey roc-plotters]$ roc ./examples/math.roc
roc: /lib64/libtinfo.so.6: no version information available (required by roc)
── FILE PROBLEM ────────────────────────────────────────────────── UNKNOWN.roc ─

I tried to read this file, but ran into a is a directory problem.[jan@framey roc-plotters]$ ls examples/
hello_world      hello_world.roc  math.roc  scatter.png        scatter.roc  shapes.jpg
hello_world.png  math             math.svg  ScatterRandom.roc  shapes       shapes.roc
[jan@framey roc-plotters]$ roc version
roc: /lib64/libtinfo.so.6: no version information available (required by roc)
roc nightly pre-release, built from commit 6613e9d on Mi 14 Sep 2022 09:12:53 UTC
[jan@framey roc-plotters]$ 
```

**Comment by Anton-4** [comment]
You do have a talent for finding strange errors :smile: 
I'll give this a try in 15 mins.

**Comment by kili-ilo** [comment]
@Anton-4 no rush, thank you for offering to help! I'm sure I'll find something else wacky in a half hour, haha

**Comment by Anton-4** [comment]
So I'm pretty confident this is because `examples/hello_world.roc` does not use the new way to refer to the platform file, namely; `packages { pf: "platform/main.roc" }`.
The error is terrible though, I'll make an issue for that.

**Comment by kili-ilo** [comment]
Good catch, thank you!

**Comment by kili-ilo** [comment]
Promising progress, but now `roc_std` is a problem:
```
[jan@framey roc-plotters]$ roc examples/math.roc 
roc: /lib64/libtinfo.so.6: no version information available (required by roc)
🔨 Rebuilding platform...
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: https://github.com/roc-lang/roc/issues/new/choose
thread 'main' panicked at 'Undefined Symbol in relocation, (+472, Relocation { kind: PltRelative, encoding: Generic, size: +20, target: Symbol(SymbolIndex(+34)), addend: +fffffffffffffffc, implicit_addend: false }): Ok(Symbol { name: "sin", address: +0, size: +0, kind: Unknown, section: Undefined, scope: Unknown, weak: false, flags: Elf { st_info: +10, st_other: +0 } })', crates/linker/src/lib.rs:2749:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[jan@framey roc-plotters]$ 
```

**Comment by kili-ilo** [comment]
This is affected (and blocked?) by https://github.com/roc-lang/roc/issues/3609

**Comment by Anton-4** [comment]
Yes, blocked is correct.

**Comment by kili-ilo** [comment]
Closing for staleness

**Pull request closed without merging**
